# M2 php-mongo-orm framework sample config
m2:
  
  # usually we define host mongo in /etc/hosts
  # define it too or place your mongo host there
  # check http://www.mongodb.org/display/DOCS/Connections for connection string format
  connect: mongo

  # Collection Aliases
  alias:
    Alias: db.collection
    Alias2: server:db.collection

    Base: test.base
    Typed: test.typed
    Something: test.something

  # Form 1: DB => collections
  db:
     collection:
         # collection config
         config: value 

  # Form 2: DB.Collection
  db.collection:
         # collection config
         config: value

  # test database
  test:

    # collection: test.base
    # untyped collection
    base:
      parf: custom-param
      field:
        name_alias: ["alias", "name"]
        name-alias: ["alias", "name"]

    # collection: test.something
    something:
       class: M_Something
       field:
         RelationField: ["has-one", "key", "db.collection"]
         Manager:       ["has-one", "m_id", "test.something"]
         Base:          ["has-one", "base_id", "test.base"]
         RelationField: ["has-many", "key", "db.collection.key"]
         Subordinates:  ["has-many", "_id", "test.something.m_id"]

    no_autoload:
      # "" means no fields
      autoload: ""

    # _id only autoload 
    id_autoload:
      autoload: _id

    # specific fields autoload
    sf_autoload:
      autoload: "name age mmm"

    typed:
      field:
        big_fat_int: ["alias", "int"]
        array_of_ip: ["alias", "aip"]
        int:         int
        arr:         array
        t.s:         string
        t.i:         int
        t.a:         array
        t.f:         float
        t.b:         bool
        t.d:         date
        t.ip:        ip
        ai:          ["array", "int"]
        as:          ["array", "string"]
        aip:         ["array", "ip"]
        aip.2:       ip
        en:          ["enum", "name", "age", "sex"]
        map:
            0: enum
            y: yksi
            ka: kaksi
            ko: kolme
        date:        date
        datetime:    DateTime
        ph:          phone
        ip:          ip
        usd:         price
        dt:          datetime
        u:           url       # url verification and prefixing
        text:        text      # html escaping, cross-site scripting
        str:         string    # just a string
        name:        name      # letters and spaces

    # strict fields
    # you can use only defined fields
    strict:
      class: M_Object
      strict: 1
      field:
        name:  ["alias", "n"]
        n:     string
        phone: ["alias", "p"]
        p:     phone
        map:   ["enum", "one", "two", "three"]
        age:   int

# alternative server connection
m2-server2:
  connect: mongo2
