# M2 php-mongo-orm framework sample config
m2:
  
  # usually we define host mongo in /etc/hosts
  # define it too or place your mongo host there
  # check http://www.mongodb.org/display/DOCS/Connections for connection string format
  connect: mongo

  # Collection Aliases
  alias:
    Alias: db.collection
    Alias2: server:db.collection

    Base: test.base
    Typed: test.typed
    Something: test.something

  # Form 1: DB => collections
  db:
     
     collection:
         # collection config
         config: value 

  # Form 2: DB.Collection
  db.collection:
         # collection config
         config: value
 
  # test database
  test:

    # collection: test.base
    # untyped collection
    base:
      parf: custom-param
      field-alias:
        name_alias: name
        name-alias: name

    # collection: test.something
    something:
       class: M_Something
       # relations
       has-one:
         RelationField: ["key", "db.collection"]
         Manager: ["m_id", "test.something"]
         Base: ["base_id", "test.base"]
       has-many:
         RelationField: ["key", "db.collection.key"]
         Subordinates: ["_id", "test.something.m_id"]

    no_autoload:
      # "" means no fields
      autoload: ""

    # _id only autoload 
    id_autoload:
      autoload: _id

    # specific fields autoload
    sf_autoload:
      autoload: "name age mmm"

    typed:
      field-alias:
        big_fat_int:int
        array_of_ip:aip
      field:
        int:int
        arr:array
        t.s:string
        t.i:int
        t.a:array
        t.f:float
        t.b:bool
        t.d:date
        t.ip:ip
        ai.*:int
        as.*:string
        aip.*:ip
        aip.2:ip
        en: ["name", "age", "sex"]
        map:
            y: yksi
            ka: kaksi
            ko: kolme
        date: date
        datetime: DateTime
        ph: phone
        ip: ip
        usd: price
        dt: datetime
        u: url     # url verification and prefixing
        text: text   # html escaping, cross-site scripting 
        str: string
        name: name
# alternative server connection
m2-server2:
  connect: mongo2
